### ISSUE TITLE
Pytorch CQ-NSGT reconstruction error=9e-01 on non-sliced version

### ISSUE THREAD

**Issue by nnanos** [sevagh/nsgt#3]
Hi sevagh,

I am trying to feed the original architecture of the OPEN-UNMUX model with the pytorch version of the CQ-NSGT that you have created.
The problem is that I cant get perfect reconstruction in the non-sliced version (in the matrix-form and not matrix-form case).
I only achieved nearly perfect reconstruction (9e-07) in the slicedCQ and not matrix-form case  (But i would like to do the experiments with the non-sliced matrix-form case). 

Any suggestion on how to run the scripts you have created (properly) on a linux machine with no sudo credentials (so i cannot install the setup.py file and just working directly withe repo) .

Thank you for your great work.

**Comment by sevagh** [comment]
Which parameters of CQ-NSGT did you use? I noticed that the reconstruction error for specific, small transforms (e.g. 10 bins, or something) can be significantly bigger than a bigger transform with more coefficients.

**Comment by sevagh** [comment]
With the help of @mattpitkin in the xumx-sliCQ repo (https://github.com/sevagh/xumx-sliCQ/commit/f82bde2a823811c029a3c0e4ae8c05b1157de039), where I use a copy of this same nsgt library, the reconstruction error has been fixed in this commit: https://github.com/sevagh/nsgt/commit/3f1b601031b7af9d6503712992c606e973f5ad55

In fact even though the matrixform had lower reconstruction error (~1e-13 for my tested params), it still wasn't as low as the fixed ragged form (1e-16), but I added the same Hermitian fft symmetry thing to the matrixform.
